project_id = "cqivqqhshxetmecpzcsr"

[functions.generate-report]
verify_jwt = false

[functions.parse-article]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.transform-articles]
verify_jwt = false

[functions.auto-publish]
verify_jwt = false

[functions.one-click-publish]
verify_jwt = false

[functions.sitemap-txt]
verify_jwt = false
